apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: result-voting-app
spec:
  ports:
   - port: 6379
     targetPort: 6379
  selector:
       name: result-app-pod
       app: result-voting-app   